require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/groceries", type: :request do
  let(:user) { create(:user) }
  let(:workspace) { create(:workspace) }
  let!(:workspace_user) { create(:workspace_user, user: user, workspace: workspace) }
  let!(:grocery_category) { create(:grocery_category) }
  let!(:grocery) { create(:grocery) }
  let!(:grocery_category_tag) { create(:grocery_category_tag, grocery: grocery, grocery_category: grocery_category) }

  before {
    login_as(user)
    patch "/workspaces/#{workspace.id}/switch"
  }

  describe "GET /groceries_search?q=MyString" do
    it "renders a successful response" do
      get search_groceries_url(:q => "MyString")
      expect(response).to be_successful
    end
  end
end
