--- !ruby/object:Jumpstart::Configuration
application_name: Orealis
business_name: Orealis Company, LLC
domain: orealis.herokuapp.com
support_email: chileapchhin+orealis@gmail.com
default_from_email: Orealis <chileapchhin+orealis@gmail.com>
business_address: ''
background_job_processor: sidekiq
email_provider: sendgrid
solargraph: false
apns: false
fcm: false
collect_billing_address: true
personal_workspaces: true
register_with_workspace: false
omniauth_providers:
- google-oauth2
- microsoft_graph
integrations:
- sentry
