--- !ruby/object:Jumpstart::Configuration
application_name: My Mega App
business_name: My Mega App
domain: mymegaapp.com
support_email: chileapchhin12@gmail.com
default_from_email: Mega App <chileapchhin12@gmail.com>
business_address: ''
background_job_processor: sidekiq
email_provider: sendgrid
solargraph: false
apns: false
fcm: false
collect_billing_address: true
personal_workspaces: true
register_with_workspace: false
omniauth_providers:
- google-oauth2
- microsoft_graph
integrations:
- sentry
